"""init

Revision ID: 24850acdb01a
Revises: 
Create Date: 2024-07-24 11:29:38.248241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24850acdb01a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memes')
    # ### end Alembic commands ###
